[Editor]
FontFamily = "JetBrains Mono"
FontSize = 14

CachedDrawing = false

## Neovim external UI features
## The following is the default value of goneovim.
## You can change the behavior of the GUI by changing the following boolean values.
## If you prefer the traditional Vim UI, set it to false for all. 
## Also, `ExtMessages` is still experimental at this time and we don't recommend setting it to true if you want stability.
ExtCmdline   = true
ExtPopupmenu = true
ExtTabline   = true
ExtMessages  = false

## This option makes the whole GUI window in semi-transparent.
## This setting also implicitly enables the Drawborder setting
Transparent = 0.925

## Draw built-in indent guide
IndentGuide = true

## Draw border on a float window
# DrawBorderForFloatWindow = false

## Draw shadow under a float window
# DrawShadowForFloatWindow = false

# Display the effect when clicked
ClickEffect = false

[Palette]
## Specifies the proportion of the command line palette to the height of the entire window.
AreaRatio = 0.5
## Specifies the number of items to be displayed in the command line palette.
MaxNumberOfResultItems = 30
## Specifies the opacity of the command line palette.
Transparent = 0.9

## The statusline configuration below relates to the display of Goenovim's own external status lines.
## If you want to use neovim's status line plugin, you should disable its display. 
[Statusline]
## Whether or not to display the external status line
Visible = true

## Options: "textLabel" / "icon" / "background" / "none"
# ModeIndicatorType = "textLabel"

## Optional setting colors per Neovim editing modes
# NormalModeColor = "#3cabeb"
# CommandModeColor = "#5285b8"
# InsertModeColor = "#2abcb4"
# ReplaceModeColor = "#ff8c0a"
# VisualModeColor = "#9932cc"
# TerminalModeColor = "#778899"

## Statusline components
# Left = [ "mode", "filepath", "filename" ]
# Right = [ "message", "git", "filetype", "fileformat", "fileencoding", "curpos", "lint" ]

[Tabline]
## Whether or not to display the external tabline
Visible = true

[Popupmenu]
## neovim's popupmenu is made up of word, menu and info parts.
## Each of these parts will display the following information.
##   word:   the text that will be inserted, mandatory
##   menu:   extra text for the popup menu, displayed after "word"
##   info:   more information about the item, can be displayed in a preview window

## The following options specify whether to display a dedicated column in the popupmenu
## to display the long text displayed in the `info` part.
ShowDetail = true

## total number to display item
Total = 20

## width of `menu` column
MenuWidth = 400

## width of `info` column
InfoWidth = 1

## width of `detail` column
DetailWidth = 250

[Lint]
## Specifies whether the external linter tooltip should be displayed or not.
Visible = true

[MiniMap]
## To view the minimap, launch an additional nvim instance;
## setting Disable to true will not launch this additional nvim instance
## and will completely disable the minimap feature.
Disable = false

## Specifies whether to show the minimap or not.
Visible = false

## Specifies the width of the minimap.
Width = 120

[ScrollBar]
## Specifies whether to show the external scrollbar or not.
Visible = true

[SideBar]
## Specifies whether to show the external sidebar or not.
Visible = false

## Specify whether or not to draw a shadow under the sidebar.
DropShadow = false

## Specify the sidebar width
Width = 200

## Specify the color to use when selecting items in the sidebar or palette in hexadecimal format
AccentColor = "#5596ea"

[Workspace]
## This setting sets the format of the path string of CWD in the sidebar.
##  name: directoryname
##  full: /path/to/directoryname
##  minimum: /p/t/directoryname
PathStyle = "minimum"

## Specifies whether the last exited session should be restored at the next startup.
RestoreSession = false

[FileExplore]
## Specify the maximum number of items to be displayed in the file explorer.
MaxDisplayItems = 30
